server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Importing common properties from config server.
  config:
    import: configserver:http://localhost:8085

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8080/eureka